# Generated by Django 5.0.3 on 2024-03-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_remove_quote_tags_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.CharField(),
        ),
    ]
